
keep_files: ['stylesheets', 'js', 'files', 'images/']

environment: "production"
url: "https://mncalculator.schellenberg.site"

site-name: Masternode ROI Calculator


plugins: [jekyll-paginate, jekyll-paginate-v2]


